package constants

const (
	// MOUSE BUTTON ACTIONS
	MOUSE_RELEASED 		= 0
	MOUSE_PRESSED 		= 1
	NO_CHANGE 			= 2

	// RADIO BUTTION ORIENT ALIGNMENT
	VERTICAL_ORIENT 	= 3
	HORISONT_ORIENT     = 4

	// BOX COMPOSITION ALIGNMENTS
	ALIGN_CENTRE 		= 5
	ALIGN_TOP_CENTRE 	= 6
	ALIGN_BOTTOM_CENTRE = 7
	
	ALIGN_TOP_LEFT 		= 8
	ALIGN_TOP_RIGHT   	= 9

	ALIGN_BOTTOM_LEFT  	= 10
	ALIGN_BOTTOM_RIGHT  = 11

	ALIGN_CENTRE_LEFT   = 12
	ALIGN_CENTRE_RIGHT  = 13

	// COLUMN COMPOSITION ALIGNMENTS
	ALIGN_LEFT 			= 14
	ALIGN_RIGHT  		= 15
	ALIGN_CENTRE_COLUMN	= 16

	// ROW COMPOSITION ALIGNMENTS
	ALIGN_TOP 			= 17
	ALIGN_BOTTOM  		= 18
	ALIGN_CENTRE_ROW	= 19

	// RECTANGLE FILL MODES
	FILL_MASTER_DIMENSIONS 	= 20
	NO_FILL 				= 21

	// RECTANGLE POSITION MODES
	MATCH_MASTER_POSITION = 22
	NO_MATCH_POSITION = 23
	
)

